"""Build one self-contained Windmill script from the canonical modules."""

from pathlib import Path
import json


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "modules"
TARGET = ROOT / "f" / "questy" / "run_all_accounts.py"
MODULES = (
    "api.py",
    "accounts.py",
    "filters.py",
    "gateway.py",
    "notifications.py",
    "quest.py",
    "rpc.py",
    "runner.py",
)


def main():
    sources = {
        name[:-3]: (SOURCE / name).read_text(encoding="utf-8")
        for name in MODULES
    }
    sources["cli_service"] = (SOURCE / "cli.py").read_text(encoding="utf-8").split(
        "\ndef cmd_tui", 1
    )[0]

    module_order = [
        "api",
        "accounts",
        "filters",
        "gateway",
        "notifications",
        "quest",
        "rpc",
        "runner",
        "cli_service",
    ]
    serialized_sources = json.dumps({name: sources[name] for name in module_order})
    generated = f'''"""Generated by tools/prepare_windmill.py. Do not edit manually."""

import json
import sys
import types
import requests as _requests_dependency
import websocket as _websocket_dependency


_PACKAGE = "_questy_runtime"
_SOURCES = {serialized_sources}
_package = types.ModuleType(_PACKAGE)
_package.__path__ = []
sys.modules[_PACKAGE] = _package


def _load_module(name):
    module_name = f"{{_PACKAGE}}.{{name}}"
    module = types.ModuleType(module_name)
    module.__file__ = f"<questy:{{name}}>"
    module.__package__ = _PACKAGE
    sys.modules[module_name] = module
    exec(compile(_SOURCES[name], module.__file__, "exec"), module.__dict__)
    return module


for _module_name in {module_order!r}:
    _load_module(_module_name)

parse_accounts = sys.modules[f"{{_PACKAGE}}.accounts"].parse_accounts
run_all_accounts = sys.modules[f"{{_PACKAGE}}.cli_service"].run_all_accounts
safe_json = sys.modules[f"{{_PACKAGE}}.notifications"].safe_json
send_webhook = sys.modules[f"{{_PACKAGE}}.notifications"].send_webhook


def _get_variable(path):
    import wmill

    return wmill.get_variable(path)


def main(
    accounts: list[dict],
    account: str = "all",
    task_types: list[str] | None = None,
    statuses: list[str] | None = None,
    auto_enroll: bool = True,
    enable_rpc: bool = True,
    enable_gateway: bool = True,
    dry_run: bool = False,
    notify: bool = True,
):
    results = {{}}
    run_error = None
    notification_sent = False
    notification_error = None

    try:
        results = run_all_accounts(
            parse_accounts(accounts),
            log=print,
            auto_enroll=auto_enroll,
            enable_rpc=enable_rpc,
            enable_gateway=enable_gateway,
            account=account,
            task_types=task_types,
            statuses=statuses or ["actionable"],
            dry_run=dry_run,
        )
    except Exception as exc:
        run_error = str(exc)
        print(f"Questy run failed: {{run_error}}")
    finally:
        try:
            if notify:
                webhook_url = _get_variable("f/questy/notification_webhook")
                if not webhook_url:
                    raise ValueError("f/questy/notification_webhook is empty")
                notification_sent = send_webhook(
                    webhook_url,
                    results or {{"_run": {{"errors": [run_error or "run failed"], "statuses": {{}}}}}},
                )
        except Exception as exc:
            notification_error = f"notification failed: {{exc}}"
            print(notification_error)

    return {{
        "success": (
            not run_error
            and not notification_error
            and not any(item["errors"] for item in results.values())
        ),
        "notification_sent": notification_sent,
        "notification_error": notification_error,
        "results": safe_json(results),
        "run_error": run_error,
    }}
'''
    TARGET.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
